In [3]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])
c = a * b   # a, b 都是2x3的二维数组
print("同形数组相乘:\n", c)

# shape属性不一样, 但是后缘维度相同, 会使用numpy的广播机制, 可以执行相互运算
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8])
c = a + b
print("不同形, 但后缘轴相同, 但可以通过广播完成运算:\n", c)

# shape属性不一样, 但是有一个数组后缘轴长度为1, 会使用numpy的广播机制, 可以执行相互运算
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10], [20]])
c = a + b   # a是2x3的二维数组, b是一个2x1的二维数组, b的后缘轴长度为1, 可以执行相互运算
print("不同形, 但某一数组后缘轴长度为1, 可以通过广播完成运算:\n", c)

同形数组相乘:
 [[ 7 16]
 [27 40]
 [55 72]]
不同形, 但后缘轴相同, 但可以通过广播完成运算:
 [[ 8 10]
 [10 12]
 [12 14]]
不同形, 但某一数组后缘轴长度为1, 可以通过广播完成运算:
 [[11 12 13]
 [24 25 26]]
