In [2]:
import numpy as np


a = np.arange(0, 5)
b = np.arange(10, 15)

c = np.add(a, b)

print(c)

[10 12 14 16 18]


In [3]:
# 聚合函数, 沿着某一维进行聚合, 然后得出值
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 通过ndarray方法中的参数axis
ret = matrix.max(axis=0)   # 第一个轴, 即列, 将会输出矩阵每一列中最大的值
print(ret)

# 通过numpy.max()函数中的参数axis
ret = np.max(matrix, axis=1)   # 第二个轴, 即行, 将会输出矩阵每一行中的最大值
print(ret)

[7 8 9]
[3 6 9]


In [17]:
# 排序函数
# 使用归并排序, 将二维数组以第二轴(即行)排序, 返回新的排序后的数组
sorted_matrix = np.sort(matrix, axis=1, kind="mergesort")

# 对于结构体数组, 可以使用order参数指定排序的依据
struct_type = [("Name", "S32"), ("Height", float), ("Age", int)]
values = [("Li", 1.8, 29), ("Zhang", 1.7, 26), ("Pu", 1.74, 32)]
struct_arr = np.array(values, dtype=struct_type)
print("未排序的数组:\n", struct_arr)
# 使用快速排序, 将二维数组以第一轴(即列)排序, 先按照Age, 再按照Height排序
sorted_arr = np.sort(struct_arr, axis=0, order=["Age", "Height"])
print("排序后的数组:\n", sorted_arr)

# 排序索引
arr = np.arange(7)
np.random.shuffle(arr)
print("原数组:", arr)
# 使用堆排序, 获取排序后对比元素组的索引
index_arr = np.argsort(arr, kind="heapsort")
print("从小到大的索引为:", index_arr)
print("则排序数组为:", arr[index_arr])
# 根据键进行排序, 获得排序后的索引
names = np.array(["Nin", "Huang", "Qian", "Cheng"])
scores = np.array([80, 78, 91, 84])
index_arr = np.lexsort((names, scores))
print("排序后的下标:", index_arr)
print("对应的数组值\n", (np.vstack((names[index_arr], scores[index_arr])).T))


未排序的数组:
 [(b'Li', 1.8 , 29) (b'Zhang', 1.7 , 26) (b'Pu', 1.74, 32)]
排序后的数组:
 [(b'Zhang', 1.7 , 26) (b'Li', 1.8 , 29) (b'Pu', 1.74, 32)]
原数组: [2 1 5 3 4 6 0]
从小到大的索引为: [6 1 0 3 4 2 5]
则排序数组为: [0 1 2 3 4 5 6]
排序后的下标: [1 0 3 2]
对应的数组值
 [['Huang' '78']
 ['Nin' '80']
 ['Cheng' '84']
 ['Qian' '91']]
