In [5]:
import numpy as np


# 使用array()函数从已知的序列中创建ndarray对象
arr1 = np.array([val for val in range(1, 16)])
print("所生成的数组:", arr1)
# 通过更改shape属性, 更改为一个5*3的矩阵
arr1.shape = (5, 3)
print("转换为矩阵", arr1.shape, '\n', arr1, '\n')


# 使用arange()函数从指定区间创建ndarray对象
arr2 = np.arange(1, 16, 1)
print("所生成的数组:", arr2)
# 通过reshape()方法, 在映射一个3*5的矩阵
arr2 = arr2.reshape(3, 5)
print("转换为矩阵", arr1.shape, '\n', arr2)


所生成的数组: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
转换为矩阵 (5, 3) 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]] 

所生成的数组: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
转换为矩阵 (5, 3) 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
# 输出转置的视图
print(arr1.T)
# 输出数组的维度
print("arr2的维度为", arr2.ndim)
# 输出数组中每个元素的字节大小
print("元素字节大小", arr1.itemsize)

[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]
arr2的维度为 2
元素字节大小 8
